task: detection

num_classes: 10
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /content/demo_count_items-3/train/
    ann_file: /content/demo_count_items-3/train/_annotations.coco.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 1
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /content/demo_count_items-3/valid/
    ann_file: /content/demo_count_items-3/valid/_annotations.coco.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 1
  drop_last: False